name: stat214
channels:
  - defaults
dependencies:
  - python
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - jupyterlab
    - seaborn
    - tensorflow
    - torch
    - pyyaml
    - tqdm
    - lightning
    - lightgbm



